server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    system:
      cpu:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      institutionService:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        writableStackTraceEnabled: false


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/agenday