server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    system:
      cpu:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
